name: Generate

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_protected == 'true' && github.sha || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:

  complete:
    if: always()
    needs: [check-generated]
    runs-on: ubuntu-latest
    steps:
    - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
      run: exit 1

  check-generated:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: make gen
    - name: Check no diffs exist
      run: git add -N . && git diff HEAD --exit-code
